"""
Phase 6 tests — narrative generation.

Architecture.md: "numbers are inserted, never generated by the LLM." These
tests exist to make that checkable rather than hoped for.
"""

from __future__ import annotations

import pytest

from app.generation.narrative import (
    MAX_ATTEMPTS,
    SYSTEM_PROMPT,
    NarrativeModel,
    SectionBrief,
    generate_report,
    generate_section,
)
from app.generation.placeholders import (
    NumberInNarrative,
    UnknownPlaceholder,
    ValueBundle,
    assert_no_literal_numbers,
    placeholders_in,
    render,
    substitute,
)
from app.rag.index import Retrieved


class FakeModel(NarrativeModel):
    name = "fake"

    def __init__(self, *drafts: str):
        self.drafts = list(drafts) or [""]
        self.calls = 0
        self.last_brief = ""

    def draft(self, system, brief):
        self.last_brief = brief
        draft = self.drafts[min(self.calls, len(self.drafts) - 1)]
        self.calls += 1
        return draft


def _bundle() -> ValueBundle:
    return (ValueBundle()
            .add("reductions_tco2e", 69672, "tCO2e", 0)
            .add("baseline_tco2e", 73438.5, "tCO2e", 1)
            .add("capacity_mw", 50, "MW", 0))


# --- formatting ------------------------------------------------------------

def test_values_use_international_grouping():
    """These figures are carried into documents read by Verra and a VVB, where
    348,358 is expected rather than 3,48,358."""
    bundle = ValueBundle().add("total", 348358, "tCO2e")
    assert bundle.values["total"] == "348,358 tCO2e"


def test_decimals_are_respected():
    assert ValueBundle().add("x", 73438.5, "tCO2e", 1).values["x"] == "73,438.5 tCO2e"


def test_a_missing_value_renders_as_a_dash_not_zero():
    """Zero is a claim; an em dash is an absence."""
    assert ValueBundle().add("x", None).values["x"] == "—"


# --- the model must not write figures -------------------------------------

@pytest.mark.parametrize("draft", [
    "The project reduces 69,672 tCO2e each year.",
    "A reduction of 69672 tonnes was achieved.",
    "Capacity is 50 MW.",
    "Performance improved by 4.2%.",
])
def test_a_literal_figure_is_rejected(draft):
    with pytest.raises(NumberInNarrative):
        assert_no_literal_numbers(draft)


def test_placeholders_are_not_mistaken_for_figures():
    assert_no_literal_numbers(
        "The project reduces {{reductions_tco2e}} against {{baseline_tco2e}}.")


@pytest.mark.parametrize("draft", [
    "Assessed under section 3.18.1 of the Standard.",
    "Applying VMR0017 and VT0008.",
    "Prepared to VCS v5.0.",
    "See Table 8 for the crediting period.",
])
def test_clause_references_are_permitted(draft):
    """They describe where a rule comes from and cannot be mistaken for a
    computed result."""
    assert_no_literal_numbers(draft)


def test_the_rejection_names_the_offending_figures():
    with pytest.raises(NumberInNarrative, match="69,672"):
        assert_no_literal_numbers("It reduces 69,672 tCO2e.")


def test_the_system_prompt_forbids_writing_numbers():
    lowered = SYSTEM_PROMPT.lower()
    assert "you never write a number" in lowered
    assert "rejected and regenerated" in lowered


# --- substitution ----------------------------------------------------------

def test_values_are_inserted():
    out = render("Reduces {{reductions_tco2e}} per year.", _bundle())
    assert out == "Reduces 69,672 tCO2e per year."


def test_a_placeholder_may_repeat():
    out = render("{{capacity_mw}} — confirmed at {{capacity_mw}}.", _bundle())
    assert out.count("50 MW") == 2


def test_whitespace_inside_a_placeholder_is_tolerated():
    assert render("Reduces {{ reductions_tco2e }}.", _bundle()).endswith("69,672 tCO2e.")


def test_an_unknown_placeholder_raises_rather_than_blanking():
    """A gap where a figure should be survives review, because the sentence
    still reads."""
    with pytest.raises(UnknownPlaceholder, match="irr_with_credits"):
        substitute("The return is {{irr_with_credits}}.", _bundle())


def test_the_error_lists_what_is_available():
    with pytest.raises(UnknownPlaceholder, match="capacity_mw"):
        substitute("{{nonexistent}}", _bundle())


def test_placeholders_in_finds_every_reference():
    assert placeholders_in("{{a}} then {{b}} then {{a}}") == ["a", "b"]


def test_render_verifies_before_substituting():
    """A draft with a literal figure must be refused even if its placeholders
    are all valid."""
    with pytest.raises(NumberInNarrative):
        render("Reduces {{reductions_tco2e}}, up 4.2% on last year.", _bundle())


# --- section generation ----------------------------------------------------

BRIEF = SectionBrief(
    heading="Summary",
    instruction="State what the project does and what it reduces.",
    placeholders=("reductions_tco2e", "capacity_mw"),
    clauses=("VMR0017 v1.0",),
    fallback="The {{capacity_mw}} project reduces {{reductions_tco2e}} annually.",
)


def test_a_clean_draft_is_rendered():
    model = FakeModel("A {{capacity_mw}} plant reducing {{reductions_tco2e}}.")
    section = generate_section(BRIEF, _bundle(), model)
    assert "50 MW" in section.text
    assert "69,672 tCO2e" in section.text
    assert section.used_model
    assert section.attempts == 1


def test_a_draft_with_a_figure_is_regenerated():
    model = FakeModel(
        "It reduces 69,672 tCO2e.",                    # rejected
        "It reduces {{reductions_tco2e}}.",            # accepted
    )
    section = generate_section(BRIEF, _bundle(), model)
    assert section.attempts == 2
    assert "69,672 tCO2e" in section.text


def test_a_persistently_bad_model_falls_back_to_the_template():
    model = FakeModel("It reduces 69,672 tCO2e.")
    section = generate_section(BRIEF, _bundle(), model)
    assert section.attempts == MAX_ATTEMPTS
    assert not section.used_model
    assert "69,672 tCO2e" in section.text
    assert "rejected" in section.note


def test_no_model_uses_the_template():
    section = generate_section(BRIEF, _bundle(), model=None)
    assert not section.used_model
    assert "50 MW" in section.text


def test_a_section_with_no_fallback_and_no_model_is_flagged_empty():
    brief = SectionBrief(heading="Site", instruction="Describe the site.")
    section = generate_section(brief, _bundle(), model=None)
    assert section.text == ""
    assert "needs an author" in section.note


def test_the_brief_lists_only_permitted_placeholders():
    model = FakeModel("{{capacity_mw}}")
    generate_section(BRIEF, _bundle(), model)
    assert "{{reductions_tco2e}}" in model.last_brief
    assert "{{baseline_tco2e}}" not in model.last_brief


def test_a_section_with_no_values_says_so_explicitly():
    brief = SectionBrief(heading="Scope", instruction="Describe the scope.")
    assert "Do not write any figure at all" in brief.as_prompt()


# --- style retrieval is optional ------------------------------------------

def test_generation_works_with_no_corpus():
    """The corpus is a separate deliverable. Blocking on it would stop the
    whole pipeline on a document handover."""
    result = generate_report([BRIEF], _bundle(),
                             FakeModel("{{capacity_mw}}"), retriever=None)
    assert result.sections[0].text
    assert not result.used_style_corpus


def test_an_empty_corpus_is_reported_not_hidden():
    result = generate_report([BRIEF], _bundle(),
                             FakeModel("{{capacity_mw}}"),
                             retriever=lambda q, h: [])
    assert any("corpus is empty" in w for w in result.warnings)


def test_style_exemplars_reach_the_brief():
    model = FakeModel("{{capacity_mw}}")
    example = Retrieved(heading="Summary", text="A «figure» plant.",
                        source="past.pdf", distance=0.1)
    generate_report([BRIEF], _bundle(), model, retriever=lambda q, h: [example])
    assert "past.pdf" in model.last_brief
    assert "FORM ONLY" in model.last_brief.upper()


def test_a_retrieval_failure_does_not_stop_generation():
    def broken(query, heading):
        raise RuntimeError("vector store unreachable")

    result = generate_report([BRIEF], _bundle(),
                             FakeModel("{{capacity_mw}}"), retriever=broken)
    assert result.sections[0].text
    assert any("retrieval failed" in w.lower() for w in result.warnings)


def test_no_model_is_reported_as_a_warning():
    result = generate_report([BRIEF], _bundle(), model=None)
    assert any("No narrative model" in w for w in result.warnings)


def test_empty_sections_are_surfaced_as_warnings():
    brief = SectionBrief(heading="Site", instruction="Describe the site.")
    result = generate_report([brief], _bundle(), model=None)
    assert any("needs an author" in w for w in result.warnings)


# --- the bridge into the report builder -----------------------------------

from datetime import date  # noqa: E402

from app.domain.classification import ProjectIntake, classify  # noqa: E402
from app.domain.constants import Technology  # noqa: E402
from app.domain.emission_factors import PowerUnit, grid_emission_factor  # noqa: E402
from app.domain.baseline import emission_reductions  # noqa: E402
from app.domain.pdd_content import ProjectIdentity, build_pdd_content  # noqa: E402
from app.generation.bridge import (  # noqa: E402
    SECTION_CLAUSES,
    SECTION_PLACEHOLDERS,
    briefs_from_sections,
    build_value_bundle,
)


def _project():
    intake = ProjectIntake(
        name="Aligarh Solar One", proponent="Bodhi Hub Client",
        country_iso2="IN", technology=Technology.SOLAR_PV_TERRESTRIAL,
        installed_capacity_mw=50.0, expected_annual_generation_mwh=87_600.0,
        initial_crediting_period_start=date(2026, 3, 1))
    cls = classify(intake)
    grid = [
        PowerUnit("C1", 50_000, 2012, efficiency=0.35,
                  efficiency_fuel_ef_t_per_gj=0.0946),
        PowerUnit("C2", 30_000, 2021, efficiency=0.38,
                  efficiency_fuel_ef_t_per_gj=0.0946),
    ]
    ef = grid_emission_factor(grid, intake.technology, 1)
    er = emission_reductions(87_600, ef.ef_grid_cm, eg_facility_mwh=87_600,
                             technology=intake.technology)
    return intake, cls, ef, er


def test_the_bundle_carries_engine_figures():
    intake, cls, ef, er = _project()
    bundle = build_value_bundle(intake, cls, ef, er)
    assert bundle.values["capacity_mw"] == "50 MW"
    assert "tCO2/MWh" in bundle.values["ef_grid_cm"]
    assert "tCO2e" in bundle.values["reductions_tco2e"]


def test_percentages_are_formatted_here_not_in_prose():
    """The model cannot multiply by 100 because it cannot write a number."""
    from app.domain.additionality import FinancialInputs, assess_additionality

    intake, cls, ef, er = _project()
    add = assess_additionality(
        FinancialInputs(capex=40_000, annual_opex=500,
                        annual_generation_mwh=87_600, tariff_per_mwh=0.03,
                        project_lifetime_years=25, discount_rate=0.10,
                        benchmark_irr=0.14, credit_price_per_tco2e=0.008,
                        annual_credits_tco2e=er.emission_reductions_tco2e),
        n_all=10, n_diff=9, project_capacity_mw=50.0, regulatory_surplus=True)
    bundle = build_value_bundle(intake, cls, ef, er, add)
    assert bundle.values["benchmark_irr"] == "14.00 %"


def test_briefs_keep_the_deterministic_prose_as_fallback():
    """Nothing is lost if the model is unavailable or writes badly."""
    intake, cls, ef, er = _project()
    bundle = build_value_bundle(intake, cls, ef, er)
    sections = {"Baseline Emissions": ["BE_y is computed as follows."]}
    briefs = briefs_from_sections(sections, bundle, SECTION_PLACEHOLDERS,
                                  SECTION_CLAUSES)
    assert briefs[0].fallback == "BE_y is computed as follows."


def test_a_section_is_offered_only_its_own_figures():
    """A model offered a figure it has no business mentioning will find a way
    to mention it."""
    intake, cls, ef, er = _project()
    bundle = build_value_bundle(intake, cls, ef, er)
    briefs = briefs_from_sections(
        {"Project Emissions": ["Nil."]}, bundle,
        SECTION_PLACEHOLDERS, SECTION_CLAUSES)
    assert briefs[0].placeholders == ("project_tco2e",)


def test_an_unlisted_section_is_offered_no_figures():
    intake, cls, ef, er = _project()
    bundle = build_value_bundle(intake, cls, ef, er)
    briefs = briefs_from_sections({"Some New Section": ["Text."]}, bundle)
    assert briefs[0].placeholders == ()


def test_without_a_narrator_the_report_is_unchanged():
    """The narrative pass must be a pure addition — no narrator, no
    difference."""
    intake, cls, ef, er = _project()
    before = build_pdd_content(intake, cls, ProjectIdentity(), ef, er)
    after = build_pdd_content(intake, cls, ProjectIdentity(), ef, er,
                              narrator=None)
    assert before.sections == after.sections


def test_with_a_narrator_sections_are_redrafted():
    intake, cls, ef, er = _project()
    model = FakeModel("Baseline emissions are {{baseline_tco2e}} per year.")
    content = build_pdd_content(intake, cls, ProjectIdentity(), ef, er,
                                narrator=model)
    text = " ".join(content.sections["Baseline Emissions"])
    assert "tCO2e per year" in text
    assert "{{" not in text


def test_a_failing_model_leaves_the_deterministic_prose_intact():
    intake, cls, ef, er = _project()
    before = build_pdd_content(intake, cls, ProjectIdentity(), ef, er)
    model = FakeModel("Baseline emissions are 73,438.5 tCO2e per year.")
    after = build_pdd_content(intake, cls, ProjectIdentity(), ef, er,
                              narrator=model)
    assert after.sections["Baseline Emissions"] == \
        before.sections["Baseline Emissions"]


def test_template_text_may_contain_figures():
    """The no-literal-numbers rule governs model output, not our own prose.
    The quantification sections are arithmetic — verifying them would reject
    the text the fallback exists to preserve."""
    brief = SectionBrief(
        heading="Baseline Emissions",
        instruction="State the baseline.",
        placeholders=("baseline_tco2e",),
        fallback="BE_y = 87,600 MWh x 0.8383 tCO2/MWh = {{baseline_tco2e}}.")
    section = generate_section(brief, _bundle(), model=None)
    assert "87,600 MWh" in section.text
    assert "73,438.5 tCO2e" in section.text


def test_a_template_placeholder_the_engine_did_not_produce_still_raises():
    brief = SectionBrief(heading="X", instruction="Y",
                         fallback="Value is {{not_computed}}.")
    with pytest.raises(UnknownPlaceholder):
        generate_section(brief, _bundle(), model=None)
