"""
Phase 6 tests — narrative generation.

Architecture.md: "numbers are inserted, never generated by the LLM." These
tests exist to make that checkable rather than hoped for.
"""

from __future__ import annotations

import pytest

from app.generation.narrative import (
    MAX_ATTEMPTS,
    SYSTEM_PROMPT,
    NarrativeModel,
    SectionBrief,
    generate_report,
    generate_section,
)
from app.generation.placeholders import (
    NumberInNarrative,
    UnknownPlaceholder,
    ValueBundle,
    assert_no_literal_numbers,
    placeholders_in,
    render,
    substitute,
)
from app.rag.index import Retrieved


class FakeModel(NarrativeModel):
    name = "fake"

    def __init__(self, *drafts: str):
        self.drafts = list(drafts) or [""]
        self.calls = 0
        self.last_brief = ""

    def draft(self, system, brief):
        self.last_brief = brief
        draft = self.drafts[min(self.calls, len(self.drafts) - 1)]
        self.calls += 1
        return draft


def _bundle() -> ValueBundle:
    return (ValueBundle()
            .add("reductions_tco2e", 69672, "tCO2e", 0)
            .add("baseline_tco2e", 73438.5, "tCO2e", 1)
            .add("capacity_mw", 50, "MW", 0))


# --- formatting ------------------------------------------------------------

def test_values_use_international_grouping():
    """These figures are carried into documents read by Verra and a VVB, where
    348,358 is expected rather than 3,48,358."""
    bundle = ValueBundle().add("total", 348358, "tCO2e")
    assert bundle.values["total"] == "348,358 tCO2e"


def test_decimals_are_respected():
    assert ValueBundle().add("x", 73438.5, "tCO2e", 1).values["x"] == "73,438.5 tCO2e"


def test_a_missing_value_renders_as_a_dash_not_zero():
    """Zero is a claim; an em dash is an absence."""
    assert ValueBundle().add("x", None).values["x"] == "—"


# --- the model must not write figures -------------------------------------

@pytest.mark.parametrize("draft", [
    "The project reduces 69,672 tCO2e each year.",
    "A reduction of 69672 tonnes was achieved.",
    "Capacity is 50 MW.",
    "Performance improved by 4.2%.",
])
def test_a_literal_figure_is_rejected(draft):
    with pytest.raises(NumberInNarrative):
        assert_no_literal_numbers(draft)


def test_placeholders_are_not_mistaken_for_figures():
    assert_no_literal_numbers(
        "The project reduces {{reductions_tco2e}} against {{baseline_tco2e}}.")


@pytest.mark.parametrize("draft", [
    "Assessed under section 3.18.1 of the Standard.",
    "Applying VMR0017 and VT0008.",
    "Prepared to VCS v5.0.",
    "See Table 8 for the crediting period.",
])
def test_clause_references_are_permitted(draft):
    """They describe where a rule comes from and cannot be mistaken for a
    computed result."""
    assert_no_literal_numbers(draft)


def test_the_rejection_names_the_offending_figures():
    with pytest.raises(NumberInNarrative, match="69,672"):
        assert_no_literal_numbers("It reduces 69,672 tCO2e.")


def test_the_system_prompt_forbids_writing_numbers():
    lowered = SYSTEM_PROMPT.lower()
    assert "you never write a number" in lowered
    assert "rejected and regenerated" in lowered


# --- substitution ----------------------------------------------------------

def test_values_are_inserted():
    out = render("Reduces {{reductions_tco2e}} per year.", _bundle())
    assert out == "Reduces 69,672 tCO2e per year."


def test_a_placeholder_may_repeat():
    out = render("{{capacity_mw}} — confirmed at {{capacity_mw}}.", _bundle())
    assert out.count("50 MW") == 2


def test_whitespace_inside_a_placeholder_is_tolerated():
    assert render("Reduces {{ reductions_tco2e }}.", _bundle()).endswith("69,672 tCO2e.")


def test_an_unknown_placeholder_raises_rather_than_blanking():
    """A gap where a figure should be survives review, because the sentence
    still reads."""
    with pytest.raises(UnknownPlaceholder, match="irr_with_credits"):
        substitute("The return is {{irr_with_credits}}.", _bundle())


def test_the_error_lists_what_is_available():
    with pytest.raises(UnknownPlaceholder, match="capacity_mw"):
        substitute("{{nonexistent}}", _bundle())


def test_placeholders_in_finds_every_reference():
    assert placeholders_in("{{a}} then {{b}} then {{a}}") == ["a", "b"]


def test_render_verifies_before_substituting():
    """A draft with a literal figure must be refused even if its placeholders
    are all valid."""
    with pytest.raises(NumberInNarrative):
        render("Reduces {{reductions_tco2e}}, up 4.2% on last year.", _bundle())


# --- section generation ----------------------------------------------------

BRIEF = SectionBrief(
    heading="Summary",
    instruction="State what the project does and what it reduces.",
    placeholders=("reductions_tco2e", "capacity_mw"),
    clauses=("VMR0017 v1.0",),
    fallback="The {{capacity_mw}} project reduces {{reductions_tco2e}} annually.",
)


def test_a_clean_draft_is_rendered():
    model = FakeModel("A {{capacity_mw}} plant reducing {{reductions_tco2e}}.")
    section = generate_section(BRIEF, _bundle(), model)
    assert "50 MW" in section.text
    assert "69,672 tCO2e" in section.text
    assert section.used_model
    assert section.attempts == 1


def test_a_draft_with_a_figure_is_regenerated():
    model = FakeModel(
        "It reduces 69,672 tCO2e.",                    # rejected
        "It reduces {{reductions_tco2e}}.",            # accepted
    )
    section = generate_section(BRIEF, _bundle(), model)
    assert section.attempts == 2
    assert "69,672 tCO2e" in section.text


def test_a_persistently_bad_model_falls_back_to_the_template():
    model = FakeModel("It reduces 69,672 tCO2e.")
    section = generate_section(BRIEF, _bundle(), model)
    assert section.attempts == MAX_ATTEMPTS
    assert not section.used_model
    assert "69,672 tCO2e" in section.text
    assert "rejected" in section.note


def test_no_model_uses_the_template():
    section = generate_section(BRIEF, _bundle(), model=None)
    assert not section.used_model
    assert "50 MW" in section.text


def test_a_section_with_no_fallback_and_no_model_is_flagged_empty():
    brief = SectionBrief(heading="Site", instruction="Describe the site.")
    section = generate_section(brief, _bundle(), model=None)
    assert section.text == ""
    assert "needs an author" in section.note


def test_the_brief_lists_only_permitted_placeholders():
    model = FakeModel("{{capacity_mw}}")
    generate_section(BRIEF, _bundle(), model)
    assert "{{reductions_tco2e}}" in model.last_brief
    assert "{{baseline_tco2e}}" not in model.last_brief


def test_a_section_with_no_values_says_so_explicitly():
    brief = SectionBrief(heading="Scope", instruction="Describe the scope.")
    assert "Do not write any figure at all" in brief.as_prompt()


# --- style retrieval is optional ------------------------------------------

def test_generation_works_with_no_corpus():
    """The corpus is a separate deliverable. Blocking on it would stop the
    whole pipeline on a document handover."""
    result = generate_report([BRIEF], _bundle(),
                             FakeModel("{{capacity_mw}}"), retriever=None)
    assert result.sections[0].text
    assert not result.used_style_corpus


def test_an_empty_corpus_is_reported_not_hidden():
    result = generate_report([BRIEF], _bundle(),
                             FakeModel("{{capacity_mw}}"),
                             retriever=lambda q, h: [])
    assert any("corpus is empty" in w for w in result.warnings)


def test_style_exemplars_reach_the_brief():
    model = FakeModel("{{capacity_mw}}")
    example = Retrieved(heading="Summary", text="A «figure» plant.",
                        source="past.pdf", distance=0.1)
    generate_report([BRIEF], _bundle(), model, retriever=lambda q, h: [example])
    assert "past.pdf" in model.last_brief
    assert "FORM ONLY" in model.last_brief.upper()


def test_a_retrieval_failure_does_not_stop_generation():
    def broken(query, heading):
        raise RuntimeError("vector store unreachable")

    result = generate_report([BRIEF], _bundle(),
                             FakeModel("{{capacity_mw}}"), retriever=broken)
    assert result.sections[0].text
    assert any("retrieval failed" in w.lower() for w in result.warnings)


def test_no_model_is_reported_as_a_warning():
    result = generate_report([BRIEF], _bundle(), model=None)
    assert any("No narrative model" in w for w in result.warnings)


def test_empty_sections_are_surfaced_as_warnings():
    brief = SectionBrief(heading="Site", instruction="Describe the site.")
    result = generate_report([brief], _bundle(), model=None)
    assert any("needs an author" in w for w in result.warnings)
