"""projects

Revision ID: 338a2acded85
Revises: de14747fad75
Create Date: 2026-08-20 09:36:08.006087
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '338a2acded85'
down_revision = 'de14747fad75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'SUBMITTED', 'ARCHIVED', name='projectstatus', native_enum=False, length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_org_created', 'projects', ['organization', 'created_at'], unique=False)
    op.create_index('ix_projects_org_name', 'projects', ['organization', 'name'], unique=True)
    op.create_index(op.f('ix_projects_organization'), 'projects', ['organization'], unique=False)
    op.add_column('documents', sa.Column('project_id', sa.UUID(), nullable=True))
    op.drop_index('ix_documents_org_hash', table_name='documents')
    op.create_index('ix_documents_project_created', 'documents', ['project_id', 'created_at'], unique=False)
    op.create_index('ix_documents_project_hash', 'documents', ['project_id', 'content_hash'], unique=True)
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_index('ix_documents_project_hash', table_name='documents')
    op.drop_index('ix_documents_project_created', table_name='documents')
    op.create_index('ix_documents_org_hash', 'documents', ['organization', 'content_hash'], unique=True)
    op.drop_column('documents', 'project_id')
    op.drop_index(op.f('ix_projects_organization'), table_name='projects')
    op.drop_index('ix_projects_org_name', table_name='projects')
    op.drop_index('ix_projects_org_created', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
