"""historical reports and chunks

Revision ID: 8594b1e667c9
Revises: c1c72922a84c
Create Date: 2026-08-14 19:19:24.577640
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

revision = '8594b1e667c9'
down_revision = 'c1c72922a84c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_reports',
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_historical_reports_org_hash', 'historical_reports', ['organization', 'content_hash'], unique=True)
    op.create_index(op.f('ix_historical_reports_organization'), 'historical_reports', ['organization'], unique=False)
    op.create_table('report_chunks',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=False),
    sa.Column('heading', sa.String(length=300), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['historical_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_chunks_organization'), 'report_chunks', ['organization'], unique=False)
    op.create_index(op.f('ix_report_chunks_report_id'), 'report_chunks', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_chunks_report_id'), table_name='report_chunks')
    op.drop_index(op.f('ix_report_chunks_organization'), table_name='report_chunks')
    op.drop_table('report_chunks')
    op.drop_index(op.f('ix_historical_reports_organization'), table_name='historical_reports')
    op.drop_index('ix_historical_reports_org_hash', table_name='historical_reports')
    op.drop_table('historical_reports')
    # ### end Alembic commands ###
