"""documents extractions review items

Revision ID: c1c72922a84c
Revises: c6416cf4ede7
Create Date: 2026-08-14 13:26:05.389983
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'c1c72922a84c'
down_revision = 'c6416cf4ede7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'EXTRACTED', 'NEEDS_REVIEW', 'MANUAL_ENTRY', 'APPROVED', name='document_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_org_created', 'documents', ['organization', 'created_at'], unique=False)
    op.create_index('ix_documents_org_hash', 'documents', ['organization', 'content_hash'], unique=True)
    op.create_index(op.f('ix_documents_organization'), 'documents', ['organization'], unique=False)
    op.create_table('extractions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('pages_read', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('can_calculate', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extractions_document_id'), 'extractions', ['document_id'], unique=False)
    op.create_index(op.f('ix_extractions_organization'), 'extractions', ['organization'], unique=False)
    op.create_table('review_items',
    sa.Column('extraction_id', sa.UUID(), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=True),
    sa.Column('observed', sa.Text(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('PENDING', 'APPROVED', 'EDITED', 'REJECTED', name='review_state'), nullable=False),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_items_extraction_id'), 'review_items', ['extraction_id'], unique=False)
    op.create_index('ix_review_items_org_state', 'review_items', ['organization', 'state'], unique=False)
    op.create_index(op.f('ix_review_items_organization'), 'review_items', ['organization'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_items_organization'), table_name='review_items')
    op.drop_index('ix_review_items_org_state', table_name='review_items')
    op.drop_index(op.f('ix_review_items_extraction_id'), table_name='review_items')
    op.drop_table('review_items')
    op.drop_index(op.f('ix_extractions_organization'), table_name='extractions')
    op.drop_index(op.f('ix_extractions_document_id'), table_name='extractions')
    op.drop_table('extractions')
    op.drop_index(op.f('ix_documents_organization'), table_name='documents')
    op.drop_index('ix_documents_org_hash', table_name='documents')
    op.drop_index('ix_documents_org_created', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
