"""project drafts

Revision ID: de14747fad75
Revises: 8594b1e667c9
Create Date: 2026-08-19 20:45:21.006538
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'de14747fad75'
down_revision = '8594b1e667c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_drafts',
    sa.Column('organization', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization', name='uq_project_drafts_organization')
    )
    op.create_index(op.f('ix_project_drafts_organization'), 'project_drafts', ['organization'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_drafts_organization'), table_name='project_drafts')
    op.drop_table('project_drafts')
    # ### end Alembic commands ###
