"""
Number insertion — Phase 6.

PRD.md: "AI-generated narrative sections (findings, recommendations, summary)
using template + calculated numbers + retrieved style examples". Architecture.md
is more precise: "numbers are inserted, never generated by the LLM".

There are two ways to honour that, and only one of them can be checked.

The weak way is to hand the model the figures and instruct it to copy them
faithfully. It usually will. When it does not — a transposed digit, a rounded
value, a figure carried from the wrong row — the output is fluent, specific and
wrong, and nothing downstream can tell.

The strong way, taken here, is that the model never receives a figure to type.
It writes with named placeholders:

    "The project is expected to reduce {{reductions_tco2e}} tCO2e each year,
     against a baseline of {{baseline_tco2e}} tCO2e."

Substitution then happens in Python from the calculation engine's own output.
A number cannot be wrong because the model never wrote one, and
`assert_no_literal_numbers` rejects any draft where it tried.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from decimal import Decimal
from typing import Any

PLACEHOLDER_PATTERN = re.compile(r"\{\{\s*([a-z0-9_]+)\s*\}\}")

# Digits that may legitimately appear in model prose without being a value.
_ALLOWED_DIGIT_CONTEXTS = (
    # Clause and section references the model is asked to cite.
    re.compile(r"\b(?:s|section|clause|para(?:graph)?|table|annex|appendix)\s?"
               r"\d+(?:\.\d+)*(?:\([a-z0-9]+\))*", re.IGNORECASE),
    re.compile(r"\b(?:v|version)\s?\d+(?:\.\d+)*[AB]?\b", re.IGNORECASE),
    re.compile(r"\b(?:VMR|VT|ACM|AM|VM|TOOL|ISO)\s?\d+\b", re.IGNORECASE),
    # Ordinal words used structurally: "the first crediting period".
    re.compile(r"\bCO2\b", re.IGNORECASE),
)


class NumberInNarrative(Exception):
    """The model wrote a figure instead of using a placeholder."""


class UnknownPlaceholder(Exception):
    """The draft references a value the calculation engine did not produce."""


@dataclass
class ValueBundle:
    """Every figure available to a narrative, already computed and formatted.

    Keys are the placeholder names a model may use. Nothing reaches a report
    that is not in here, which means the set of numbers a report can contain is
    fixed before any text is generated.
    """

    values: dict[str, str] = field(default_factory=dict)

    def add(self, name: str, value: Any, unit: str = "",
            decimals: int = 0) -> "ValueBundle":
        self.values[name] = f"{self._format(value, decimals)}{unit and ' ' + unit}"
        return self

    @staticmethod
    def _format(value: Any, decimals: int) -> str:
        if value is None:
            return "—"
        if isinstance(value, (int, float, Decimal)):
            # International grouping: these figures are carried into documents
            # read by Verra and a validation body.
            return f"{value:,.{decimals}f}"
        return str(value)

    def __contains__(self, name: str) -> bool:
        return name in self.values

    def keys(self) -> list[str]:
        return sorted(self.values)


def assert_no_literal_numbers(draft: str) -> None:
    """Reject a draft in which the model typed a figure.

    Clause references and methodology identifiers are permitted — they describe
    where a rule comes from, and none can be mistaken for a calculated result.
    Anything else with a digit in it means the model ignored the placeholder
    instruction, and the right response is to regenerate rather than to publish
    a number nobody computed.
    """
    stripped = draft
    for pattern in _ALLOWED_DIGIT_CONTEXTS:
        stripped = pattern.sub("", stripped)
    stripped = PLACEHOLDER_PATTERN.sub("", stripped)

    found = re.findall(r"\b\d[\d,]*(?:\.\d+)?\b", stripped)
    if found:
        raise NumberInNarrative(
            f"The draft contains literal figure(s): {', '.join(found[:5])}. "
            f"Narrative text must reference values as {{{{placeholders}}}} so "
            f"they are inserted from the calculation engine. Regenerate."
        )


def placeholders_in(draft: str) -> list[str]:
    return sorted(set(PLACEHOLDER_PATTERN.findall(draft)))


def substitute(draft: str, bundle: ValueBundle) -> str:
    """Insert computed values into a verified draft.

    An unknown placeholder raises rather than rendering blank. A gap in a
    sentence where a figure should be is the kind of defect that survives
    review, because the sentence still reads.
    """
    unknown = [name for name in placeholders_in(draft) if name not in bundle]
    if unknown:
        raise UnknownPlaceholder(
            f"The draft references value(s) the calculation engine did not "
            f"produce: {', '.join(unknown)}. Available: "
            f"{', '.join(bundle.keys()) or '(none)'}."
        )

    def _replace(match: re.Match[str]) -> str:
        return bundle.values[match.group(1)]

    return PLACEHOLDER_PATTERN.sub(_replace, draft)


def render(draft: str, bundle: ValueBundle) -> str:
    """Verify then substitute — the only supported path from draft to report."""
    assert_no_literal_numbers(draft)
    return substitute(draft, bundle)
